#!/usr/bin/sh
for i in {0..9}; do
   test -S "$XDG_RUNTIME_DIR"/discord-ipc-$i || ln -sf {app/com.discordapp.Discord,"$XDG_RUNTIME_DIR"}/discord-ipc-$i;
   test -S "$XDG_RUNTIME_DIR"/discord-ipc-$i || ln -sf {app/com.discordapp.DiscordCanary,"$XDG_RUNTIME_DIR"}/discord-ipc-$i;
done

export OSU_EXTERNAL_UPDATE_PROVIDER=1

if [ -n "$STRANGLE_FPS" ] && [ "$STRANGLE_FPS" != "0" ]; then
   exec /app/bin/strangle /app/bin/osu! "$@"
fi

exec '/app/bin/osu!' "$@"
