#!/usr/bin/sh
for i in {0..9}; do
   test -S "$XDG_RUNTIME_DIR"/discord-ipc-$i || ln -sf {app/com.discordapp.Discord,"$XDG_RUNTIME_DIR"}/discord-ipc-$i;
   test -S "$XDG_RUNTIME_DIR"/discord-ipc-$i || ln -sf {app/com.discordapp.DiscordCanary,"$XDG_RUNTIME_DIR"}/discord-ipc-$i;
done

# Force wayland
export SDL_VIDEODRIVER=wayland
# Enable LatencyFleX
export LFX=1
# Force disable vsync
export STRANGLE_VSYNC=0
# Prevent crash when using OpenGL renderer
export STRANGLE_NODLSYM=1

export OSU_EXTERNAL_UPDATE_PROVIDER=1

/app/bin/strangle /app/bin/osu\! "$@"
