name: CI

on:
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: osu.flatpak
          manifest-path: sh.ppy.osu.yaml
          cache-key: flatpak-builder-${{ github.sha }}
